### PR TITLE
Handle output on stderr

### LINKED ISSUE #4: Broken with newest SublimeLinter update
It seems, that this plugin is broken with the newest sublimelinter update

### PR DESCRIPTION
**Pull request by kaste**
Fixes #4 🤞

### CODE REVIEW

**Comment by xolom** [comment]
Works for me!

**Comment by kaste** [comment]
Cool, thanks for testing. Really appreciate. 

Do you know btw if clang uses stdout for anything?

**Comment by xolom** [comment]
I think it uses it only for normal compilation (informative) messages, compiler warnings and error are printed to stderr

**Comment by kaste** [comment]
Okay, thanks, that's for later. @braver released 4.3. 15 minutes before Munich-Madrid. 🙄

**Comment by braver** [comment]
Oh shit, Munich-Madrid is today? 

You're a Bayern fan too right?

**Comment by kaste** [comment]
9 minutes

**Pull request merged**
