### PR TITLE
Updated for SublimeLinter v4.0 support

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by braver** [comment]
LGTM, @kaste WDYT?

**Comment by kaste** [comment]
Ha, great. But I don't think `source.c improved` and `source.c++11` are valid. The first one also has a space in it. 

https://github.com/abusalimov/SublimeCImproved/blob/0f634d6094f4d008b0d4ebd81e2ba224ccd850e4/c-improved.syntax.yaml#L7

https://github.com/gingerBill/sublime-cpp11/blob/c632f678b45d059f2cc115dc3046a446f988af53/C%2B%2B11.sublime-syntax#L21

My own package https://github.com/kaste/HighlightScopes makes this relatively easy to spot.

**Comment by braver** [comment]
Oh, I’m a lousy reviewer, I should stop even trying. 🤦🏼‍♂️

`source.c, source.c++` is probably the selector we need here.

**Comment by kaste** [comment]
:+1: Ship it!

**Comment by jfcherng** [comment]
This change is awesome! But the hard-coded `c improved, c++11` are making this change less gorgeous.

https://github.com/SublimeLinter/SublimeLinter-clang/blob/e3504c2ba335dab9899a1a4adab7adb42f6d088a/linter.py#L59-L62

Is there a way that we do not have to hard-code them?

**Comment by kaste** [comment]
Hm. I thought the next step forward is #7 where we don't check the syntax anymore.

**Pull request merged**
